site_name: Hydrological Analysis Tools
site_url: https://ecmwf.github.io/hat/

nav:
    - Welcome: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Command Line Interface:
        - station_mapping: station_mapping.md
        - hat-extract-timeseries: hat_extract-timeseries.md
        - hat-hydrostats: hat_hydrostats.md

theme: readthedocs